### PR TITLE
move currentValue from bindings to el

### LINKED ISSUE #2: doesn't work for multiple items on the same page
Here's a slight modification of your example code-pen to illustrate the problem.

https://codepen.io/zevdg/pen/EQWZJy

### PR DESCRIPTION
**Pull request by zevdg**
fixes #2 
before this fix, currentValue was global which caused only the first element to be clamped.  This change saves the value to an [html5 data attribute](http://w3c.github.io/html/single-page.html#embedding-custom-non-visible-data-with-the-data-attributes) instead so that we can have a different currentValue per element.

### CODE REVIEW

**Comment by Frondor** [comment]
Thank you for this!

File: src/main.js [hunk 1]
```diff
@@ -1,5 +1,5 @@
 const css = 'display:block;display:-webkit-box;-webkit-box-orient:vertical;overflow:hidden;text-overflow:ellipsis'
-const currentValueProp = "data-v-line-clamp-current-value"
+const currentValueProp = "vLineClampValue"
```
Comment (zevdg) [inline src/main.js]: I chose this attribute's original name very specifically to conform to http://w3c.github.io/html/single-page.html#embedding-custom-non-visible-data-with-the-data-attributes (specifically, it starts with "data-" and it is all lowercase due to the note about automatic lowercasing)

This change you made removes both of those properties. I just wanted to make sure this was intentional and not an oversight.

Thanks for the great library and the fast code reviews!

Comment (Frondor) [reply src/main.js]: Looks like code reviews are not always that fast :wink: 

Anyway, to conform the w3c you should be using `element.dataset` property as far as I know.
If you add `kebab-case` properties to a DOM element, besides of limiting yourself to use `elem['kebab-case'']` notation (since `elem.kebab-case` throws an error), it doesn't look consistent along all the other properties, see:


It was intentional indeed, I hope you don't mind that :+1:
